### ISSUE TITLE
Defining controller, routes and models for each user type [Tarek and Mazen]

### ISSUE THREAD

**Issue by MazennW** [ramy-att/trivial-soen341project2023#13]
Continuing on #12 
The following will be implemented by @TarekElalfi and @MazennW.
Admin - Tarek
Student - Tarek
Employer - Mazen
JobPosting - Mazen
Application - Mazen

**Comment by ramy-att** [comment]
Update: only missing user is admin

**Comment by ramy-att** [comment]
Great job guys! I will close this issue and create a new one for the admin
