### ISSUE TITLE
Fix env and reset API keys

### ISSUE THREAD

**Issue by ramy-att** [ramy-att/trivial-soen341project2023#164]
Need to change all API keys like:
![image](https://user-images.githubusercontent.com/83047251/231044186-2aa0d29d-2827-45ee-95af-a595266014e2.png)

**Comment by khaled-saleh1** [comment]
![image](https://user-images.githubusercontent.com/93226474/232921610-8f7985ef-4569-4aeb-8aa8-a02f6c539329.png)

The issue was resolved and  took out the env file from Master
