### ISSUE TITLE
Edit profile page

### ISSUE THREAD

**Issue by ramy-att** [ramy-att/trivial-soen341project2023#22]
As a user, I need to be able to edit my profile. 
As a student, this means:
	"name": string, required;
	"email": email, unique, required;
	"password": password, required;
	"category": engineering | business | .... // required categories?
	"resume": file, required,
	"coverLetter": file,
	"transcript": file,
As an employer, this means:
        "name": string, required;
	"email": email, unique, required;
	"password": password, required;
	"organizationName": string, required
	"category": engineering | business | .... // required categories?
	"postings": [...jobPostings]
We should design this page before implementing it @Ziad-Tari .

**Comment by khaled106** [comment]
@Ziad-Tari  Make sure you link the issue to the branch  you were working on ! (On the right in Development Click on the setting icon and choose the branch related to the issue) 
" I have already linked the branch to the issue just make sure you do it for any other issues"
