### ISSUE TITLE
Postings: connect backend to frontend

### ISSUE THREAD

**Issue by ramy-att** [ramy-att/trivial-soen341project2023#43]
Get browsable postings from backend on refresh 

# Applying to postings as a student:

1. Navigate to postings page 
2. Choose position from the table and press apply 
3. Redirected to postings page 
4. Press apply in the top right 
5. Can submit resume, transcript, cover letter 
6. When at least the resume is submitted save the application and return a success message (error if doesn’t work)

**Comment by TarekElalfi** [comment]
Great job PR closed
